import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generatePDF(reportData) {
  const doc = new jsPDF();

  const aiFeedback = reportData?.aiFeedback || {};

  const technicalScore = reportData?.technicalScore || aiFeedback.technical_score || 0;
  const communicationScore =
    reportData?.communicationScore || aiFeedback.communication_score || 0;
  const confidenceScore =
    reportData?.confidenceScore || aiFeedback.confidence_score || 0;
  const eyeContactScore = reportData?.eyeContactScore || 0;

  const overallScore =
    reportData?.overallScore ||
    Math.round(
      (technicalScore + communicationScore + confidenceScore + eyeContactScore) / 4
    );

  doc.setFontSize(20);
  doc.text("AI Interview Analyzer Report", 20, 20);

  doc.setFontSize(11);
  doc.text(`Generated On: ${new Date().toLocaleString()}`, 20, 30);

  doc.setFontSize(14);
  doc.text("Performance Summary", 20, 45);

  autoTable(doc, {
    startY: 52,
    head: [["Metric", "Score"]],
    body: [
      ["Overall Score", `${overallScore}%`],
      ["Technical Score", `${technicalScore}%`],
      ["Communication Score", `${communicationScore}%`],
      ["Confidence Score", `${confidenceScore}%`],
      ["Eye Contact Score", `${eyeContactScore}%`],
      ["Filler Words", `${reportData?.totalFillerWords || 0}`],
      ["Duration", reportData?.duration || "00:00"],
    ],
  });

  let y = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(14);
  doc.text("Question Asked", 20, y);
  y += 8;

  doc.setFontSize(11);
  doc.text(doc.splitTextToSize(reportData?.question || "N/A", 170), 20, y);
  y += 20;

  doc.setFontSize(14);
  doc.text("Transcript", 20, y);
  y += 8;

  const transcriptLines = doc.splitTextToSize(
    reportData?.transcript || "No transcript available.",
    170
  );
  doc.setFontSize(11);
  doc.text(transcriptLines, 20, y);
  y += transcriptLines.length * 6 + 10;

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  y = addListSection(doc, "Strengths", reportData?.strengths, y);
  y = addListSection(doc, "Weaknesses", reportData?.weaknesses, y);
  y = addListSection(doc, "Suggestions", reportData?.suggestions, y);

  doc.setFontSize(10);
  doc.text("Generated by AI Interview Analyzer", 20, 285);

  doc.save("AI_Interview_Report.pdf");
}

function addListSection(doc, title, items = [], y) {
  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.text(title, 20, y);
  y += 8;

  const listItems = items.length > 0 ? items : [`No ${title.toLowerCase()} available.`];

  listItems.forEach((item) => {
    const lines = doc.splitTextToSize(`• ${item}`, 165);

    if (y + lines.length * 6 > 280) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(11);
    doc.text(lines, 25, y);
    y += lines.length * 6 + 3;
  });

  return y + 5;
}